export const actionEnum=Object.freeze({
    SET_USER_MESSAGE: 0,
    IS_AUTHORIZED: 1,
    SET_USERNAME: 2,
    SET_PASSWORD: 3,
    IS_MODIFYING: 4,
    SET_TOKEN: 5,
    SET_FIRST_NAME: 6,
    SET_LAST_NAME: 7,
    IS_USER_ACTIVE: 8,
    SET_USER_ID: 9,
    ALLOW_EMPTY_FIELDS: 10,
    SET_DEVICE_TYPE: 11
});